modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
logoFile="extended_workbench.png"
credits="Naruto1310 for being the original creator."
authors="${mod_authors}"
description='''${mod_description}'''

[[dependencies.${mod_id}]]
    modId="forge"
    mandatory=true
    versionRange="[46,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20,1.21)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="jei"
    mandatory=false
    versionRange="[14.0.0.11,)"
    ordering="NONE"
    side="CLIENT"

[[dependencies.${mod_id}]]
    modId="enderitemod"
    mandatory=false
    versionRange="[1.5.1,)"
    ordering="NONE"
    side="BOTH"
